### ISSUE TITLE
嵌套表格，区分层级(Group) 行展开时拖拽有问题

### ISSUE THREAD

**Issue by Ace10** [mizuka-wu/el-table-draggable#1]
嵌套表格，区分层级(Group) 行展开时拖拽table展示不对
![image](https://user-images.githubusercontent.com/698877/128154706-e722999f-ed82-441c-b05a-89402b547a39.png)

**Comment by mizuka-wu** [comment]
el-table做展开行是单独又开了一个tr 没办法和拖拽的那一行一起拖的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Ace10 ***@***.***>
发送时间: Wednesday, August 4, 2021 5:10:43 PM
收件人: mizuka-wu/el-table-draggable ***@***.***>
抄送: Subscribed ***@***.***>
主题: [mizuka-wu/el-table-draggable] 嵌套表格，区分层级(Group) 行展开时拖拽有问题 (#1)


嵌套表格，区分层级(Group) 行展开时拖拽table展示不对
[image]<https://user-images.githubusercontent.com/698877/128154706-e722999f-ed82-441c-b05a-89402b547a39.png>

―

**Comment by Ace10** [comment]
在onstart事件里把el-table的expand-row-keys清空可以解决，但需要拖拽两次，体验不是很好

**Comment by mizuka-wu** [comment]
你可以试一下直接操作dom结构 但是index fix的部分可能会出现问题

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Ace10 ***@***.***>
发送时间: Thursday, August 5, 2021 11:29:55 AM
收件人: mizuka-wu/el-table-draggable ***@***.***>
抄送: Edward Mizuka ***@***.***>; Comment ***@***.***>
主题: Re: [mizuka-wu/el-table-draggable] 嵌套表格，区分层级(Group) 行展开时拖拽有问题 (#1)


在onstart事件里把el-table的expand-row-keys清空可以解决，但需要拖拽两次，体验不是很好

―

**Comment by mizuka-wu** [comment]
抱歉 应该是related那边的判断有问题 那边我再想想办法

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 吴 贻| ***@***.***>
发送时间: Thursday, August 5, 2021 11:36:18 AM
收件人: mizuka-wu/el-table-draggable ***@***.***>; mizuka-wu/el-table-draggable ***@***.***>
抄送: Comment ***@***.***>
主题: Re: [mizuka-wu/el-table-draggable] 嵌套表格，区分层级(Group) 行展开时拖拽有问题 (#1)

你可以试一下直接操作dom结构 但是index fix的部分可能会出现问题

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Ace10 ***@***.***>
发送时间: Thursday, August 5, 2021 11:29:55 AM
收件人: mizuka-wu/el-table-draggable ***@***.***>
抄送: Edward Mizuka ***@***.***>; Comment ***@***.***>
主题: Re: [mizuka-wu/el-table-draggable] 嵌套表格，区分层级(Group) 行展开时拖拽有问题 (#1)


在onstart事件里把el-table的expand-row-keys清空可以解决，但需要拖拽两次，体验不是很好

―

**Comment by Ace10** [comment]
好的

**Comment by mizuka-wu** [comment]
使用1.0.1
调整了onMove的算法
