### ISSUE TITLE
1.4.12版本，elementui2.13.2版本，固定操作列底部边框没显示出来，高度计算有问题

### ISSUE THREAD

**Issue by fallenaAngel** [mizuka-wu/el-table-draggable#16]
1.4.12版本，elementui2.13.2版本，固定操作列底部边框没显示出来，高度计算有问题
![image](https://user-images.githubusercontent.com/39083913/224935798-f39e5c86-e2fa-488d-b443-85aea15174cf.png)

**Comment by mizuka-wu** [comment]
操作流程？
draggable本身不会处理渲染的相关问题

发自我的 iPhone

在 2023年3月14日，16:07，李丁丁 ***@***.***> 写道：

﻿

1.4.12版本，elementui2.13.2版本，固定操作列底部边框没显示出来，高度计算有问题
[image]<https://user-images.githubusercontent.com/39083913/224935798-f39e5c86-e2fa-488d-b443-85aea15174cf.png>
