### ISSUE TITLE
低版本element-ui的el-table没有treeProps时会出错，且无报错信息

### ISSUE THREAD

**Issue by maheavenlu** [mizuka-wu/el-table-draggable#5]
![image](https://user-images.githubusercontent.com/18388762/151110982-ebccfe22-cbbe-4a98-b104-cde6742ce5a8.png)
此处会错误

**Comment by mizuka-wu** [comment]
麻烦给一下版本号

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: maheavenlu ***@***.***>
发送时间: Wednesday, January 26, 2022 1:54:49 PM
收件人: mizuka-wu/el-table-draggable ***@***.***>
抄送: Subscribed ***@***.***>
主题: [mizuka-wu/el-table-draggable] 低版本element-ui的el-table没有treeProps时会出错，且无报错信息 (Issue #5)


[image]<https://user-images.githubusercontent.com/18388762/151110982-ebccfe22-cbbe-4a98-b104-cde6742ce5a8.png>
此处会错误

―

**Comment by mizuka-wu** [comment]
新版本已经忽略无treeProps的情况
